repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff-format
        args: [--line-length=121]
      - id: ruff-check
        args: [--fix, --line-length=121]

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        name: flake8-arda_app
        entry: flake8 arda_app/ --config .flake8
        types: [python]

      - id: flake8
        name: flake8-tests
        entry: flake8 tests/ --config .flake8-test
        types: [python]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
