include:
  - project: 'service-engineering-automation/mdso/common-ci-cd-automations'
    ref: charter_stable
    file: '/quick-start-templates/.quick-start-single-app-solution.yml'

flake8:
  allow_failure: false

plansdk-deprecated-check:
  allow_failure: true

uprev:
  allow_failure: true
