services:
  sbnoe-nginx:
    image: docker-artifactory.spectrumflow.net/docker/nginx:latest
    container_name: sbnoe-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    networks:
      - nginx-ingress
      - observability
      - sense-network
    depends_on:
      - grafana
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  nginx-ingress:
    driver: bridge
    ipam:
      config:
        - subnet: "172.16.100.0/23"
          gateway: "172.16.100.1"

  observability:
    external: true
    name: observability

  sense-network:
    external: true
    name: sense-apps_sense-network
