image: $ARTIFACTORY_REGISTRY/docker/python:3.9.11

stages:
  - quality
  - scan
  - test
  - bump_version_stage

include: 
  - /cicd/scan.yml
  - /cicd/qc.yml
  - /cicd/test.yml
  - /cicd/bump_version_stage.yml